name: aroundus_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  logger: ^1.0.0
  json_serializable: ^4.1.0
  dio: ^4.0.0
  jwt_decoder: ^2.0.1
  equatable: ^2.0.3
  formz: ^0.4.0
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  sizer: ^2.0.13
  freezed: ^0.14.1
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.10
  flutter_html: ^2.1.1
  flutter_multi_formatter: ^2.3.5
  flutter_web_frame: ^0.0.2
  flutter_sizer: ^1.0.4
  badges: ^2.0.1
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  flutter_swiper_plus: ^2.0.4
  kpostal: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
  assets:
    - assets/
    - assets/icons/
    - assets/icons/bottomNavigationBar/
    - assets/images/
    - assets/postcode.html